# Principal Components with The Iris Dataset

## Motivation

Now you may ask, why is this useful? In our example we will go from four to two dimensions, not particularly exciting. But we can take 100 or even 100,000 dimensional data and shrink it down to about 20 or so dimensions. For our machine learning algorithms this can be a huge speedup and it can avoid the machine learning algorithm's parameters fitting to noise (which is usually the lower variance elements of the dataset).

## Taking a look at the data

Ah the Iris Dataset, the classical example of dimensionality reduction. This dataset was actually the first dataset to have Principal Components Dimensionality Reduction performed on it. Let's take a look at the data. The library is actually so famous, it comes pre-loaded in R.

In [1]:
head(iris)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa

A quick explanation is required. The flowers belong to three different species: setosa, versicolor, and virginica. Of those, there is a measurement of the sepal and petal of the flower in centimeters. Let's take a summary of the data and see what it has to offer.

In [2]:
summary(iris)

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
                
                
                

Because I am more visual in nature, let's plot it. (The install may take a while but the resulting plots will be cleaner)

In [3]:
library(ggvis)
library(IRdisplay)

In [4]:
# Below is the line to create the graph but since irkernel is stupid, we are going to be roundabout and load the html
# outfile <- iris %>% ggvis(~Petal.Length, ~Petal.Width, fill = ~Species) %>% layer_points() %>% view_static() %>% htmltools::html_print()
display_html(file='index.html')

<!DOCTYPE html>
<!-- saved from url=(0053)file:///tmp/RtmpS6S0yG/viewhtml49b1c5706a9/index.html -->
 



 





 


 
 
 
 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 Petal.Length 0.0 0.2 0.4 0.6 0.8 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 Petal.Width Species setosa versicolor virginica 
 
 
 
 
 
 Renderer: 
 SVG 
 | 
 Canvas 
 
 
 Download SVG

## Principal Components Time

And now it's time for the main show, principal components. Introduced by Ronald Fischer, principal components dimensionality reduction is a way to take components in a high dimensional space and project them into a lower dimenion. 

Right now the basis is an identity matrix. Meaning that plotting component one (Petal.Length) is only determined by Petal.Length in the Dataset. We can create a new feature space where, for example, plotting component one is determine .5 * Petal.Length and .8 * Petal.Width and plot that against something similar. 

But we are going to be a little more careful about how much of each feature we pick, we are going to preserve some qualities about the data with our linear transformation. One is that we preserve the dimensions with the highest variance, the first component will represent the highest amount of variance in the data.

In [5]:
analysis <- iris[,-5]
covmat <- cov(analysis)

Now we hope that the covariance matrix is positive definite meaning that
    $$\forall {\bf u}, {\bf u^{T}} \cdot covmat(data) \cdot {\bf u} > 0$$
Meaning that we have a unique representation in lower space. If
    $${\bf u^{T}} \cdot covmat(data) \cdot {\bf u} \geq 0$$
We have many interpretations

So in order to find the linear combination that will satisfy this and a bunch of other statistical criterion we have to find the eigenvalues and the eigenvectors of the covariance matrix. Why? Because we want to preserve the original covariance of the data and it's position but just put it in a different feature space, one where a few of the dimensions have a great amount of variance and the others not so much

In [6]:
means <- colMeans(analysis)
eigs <- eigen(covmat)
eigs

$values
[1] 4.22824171 0.24267075 0.07820950 0.02383509

$vectors
            [,1]        [,2]        [,3]       [,4]
[1,]  0.36138659 -0.65658877 -0.58202985  0.3154872
[2,] -0.08452251 -0.73016143  0.59791083 -0.3197231
[3,]  0.85667061  0.17337266  0.07623608 -0.4798390
[4,]  0.35828920  0.07548102  0.54583143  0.7536574

And there you have it! The Columns of the eigs$vectors are our new feature space. The Size of the eigenvalue is the amount of explained variance meaning that...

In [7]:
eigs$values / sum(eigs$values)

[1] 0.924618723 0.053066483 0.017102610 0.005212184

The first component made out of .36 var 1, -0.08 var 2, and so on can account for most of the variance in the dataset while the last two hardly count for any. Let's take that piece and plot it. First we need to get the old data into new feature space. that should just be a dot product, let's visualize what is happening.

In [19]:
centered <- analysis-means
ploting <- centered
ploting['Species'] = iris$Species
# outfile <- ploting %>% ggvis(~Petal.Length, ~Petal.Width, fill = ~Species) %>% layer_points() %>% view_static() %>% htmltools::html_print()
display_html(file='centered.html')

<!DOCTYPE html>
<!-- saved from url=(0054)file:///tmp/Rtmp7EZCiq/viewhtml1033791b2efc/index.html -->
 



 





 


 
 
 
 -5 -4 -3 -2 -1 0 1 2 3 4 5 Petal.Length -5 -4 -3 -2 -1 0 1 Petal.Width Species setosa versicolor virginica 
 
 
 
 
 
 Renderer: 
 SVG 
 | 
 Canvas 
 
 
 Download SVG

Now we rotate the data to have the highest variance bits as the first few components

In [26]:
almost <- as.data.frame(as.matrix(centered) %*% eigs$vectors)
colnames(almost) = c('PC1', 'PC2', 'PC3', 'PC4')
ploting <- almost
ploting['Species'] = iris$Species
# outfile <- ploting %>% ggvis(~PC1, ~PC2, fill = ~Species) %>% layer_points() %>% view_static() %>% htmltools::html_print()
display_html(file='mashed.html')

<!DOCTYPE html>
<!-- saved from url=(0054)file:///tmp/Rtmp7EZCiq/viewhtml10335c7b62d1/index.html -->
 



 





 


 
 
 
 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 PC1 -4.5 -4.0 -3.5 -3.0 -2.5 -2.0 -1.5 -1.0 -0.5 0.0 0.5 1.0 1.5 PC2 Species setosa versicolor virginica 
 
 
 
 
 
 Renderer: 
 SVG 
 | 
 Canvas 
 
 
 Download SVG

Now let's add back the means and we should get our dataset back, but in a more descernable way.

In [30]:
finalized <- almost+means
finalized['Species'] <- iris$Species
# finalized %>% ggvis(~PC1, ~PC2, fill = ~Species) %>% layer_points()
display_html(file='final.html')

<!DOCTYPE html>
<!-- saved from url=(0054)file:///tmp/Rtmp7EZCiq/viewhtml1033679b1854/index.html -->
 



 





 


 
 
 
 0 1 2 3 4 5 6 7 8 PC1 -3 -2 -1 0 1 2 3 4 5 6 7 PC2 Species setosa versicolor virginica 
 
 
 
 
 
 Renderer: 
 SVG 
 | 
 Canvas 
 
 
 Download SVG

## R's Way

Now we did all that work manually. But, r has it's own packaging suite to do this for us.

In [33]:
prnc <- princomp(analysis)
summary(prnc)

Importance of components:
                          Comp.1     Comp.2     Comp.3      Comp.4
Standard deviation     2.0494032 0.49097143 0.27872586 0.153870700
Proportion of Variance 0.9246187 0.05306648 0.01710261 0.005212184
Cumulative Proportion  0.9246187 0.97768521 0.99478782 1.000000000

In [34]:
loadings(prnc)


Loadings:
             Comp.1 Comp.2 Comp.3 Comp.4
Sepal.Length  0.361 -0.657 -0.582  0.315
Sepal.Width         -0.730  0.598 -0.320
Petal.Length  0.857  0.173        -0.480
Petal.Width   0.358         0.546  0.754

               Comp.1 Comp.2 Comp.3 Comp.4
SS loadings      1.00   1.00   1.00   1.00
Proportion Var   0.25   0.25   0.25   0.25
Cumulative Var   0.25   0.50   0.75   1.00

R does some roundings and other calculations, and you can get the transformed variables here too it is a quite powerful one liner.

## Other Forms of PCA

And now we have a lower dimensional set of data that represents our original data pretty well and it keeps inherent properties about the data like scale and rotations and covariances. There are other options as well. 

Whitening the data is multiplying the product 'almost' by the eigenvalue raised to the -.5 power, namely. 
    $$x_{whiten} = x_{rotated} / \lambda$$
ZCA does the exact same formula but before you add the mean back, multiply it by the loadings matrix one more time, transposed.
    $$x_{zca} = eigenvectors \cdot x_{rotated} + mean(x)$$
    
This is in no way an exhaustive list of the dimensionality reductions inspired by principal components.

## Computational Efficiency

The intensive part of this application is getting the the covariance matrix which takes about n^3 space using our method so far and an polynomially intractable amount of time using our current method (anything other than trivial). Once your data exceeds a memory form of rows, R gives up (Unless you are using SparkR but even then R has to go through all of the data specifically when we have other ways making it hard for distrbuted systems like Apache Cassandra).

So what is the answer? For medium sized Big-Data We can use the singular value decomposition hack out our matrix to look like this.

In [36]:
sing <- svd(analysis)
sing

$d
[1] 95.959914 17.761034  3.460931  1.884826

$u
              [,1]          [,2]          [,3]          [,4]
  [1,] -0.06161685  1.296114e-01  0.0021385967  0.0016381914
  [2,] -0.05807094  1.110198e-01  0.0706723871  0.0517569646
  [3,] -0.05676305  1.179665e-01  0.0043425491  0.0095570243
  [4,] -0.05665344  1.053081e-01  0.0059246720 -0.0416438911
  [5,] -0.06123020  1.310898e-01 -0.0318810953 -0.0322148124
  [6,] -0.06750317  1.308848e-01 -0.0685371918 -0.0113642477
  [7,] -0.05748208  1.165982e-01 -0.0664136685 -0.0267433923
  [8,] -0.06097263  1.209431e-01  0.0054302657 -0.0240566566
  [9,] -0.05376120  9.994149e-02  0.0176366479 -0.0165153852
 [10,] -0.05882666  1.120431e-01  0.0649689136 -0.0304719804
 [11,] -0.06529182  1.365781e-01  0.0049358593 -0.0064694222
 [12,] -0.05994178  1.137531e-01 -0.0252977575 -0.0836045085
 [13,] -0.05711323  1.113548e-01  0.0716796746 -0.0051546938
 [14,] -0.05159575  1.153248e-01  0.0042621200 -0.0137409532
 [15,] -0.06800719  1.641831e-01  0.0095700911  0.0876360142
 [16,] -0.07076259  1.590565e-01 -0.1191426516  0.0065500061
 [17,] -0.06536474  1.468448e-01 -0.0616990077  0.0906600216
 [18,] -0.06179182  1.276765e-01 -0.0133779293  0.0415289575
 [19,] -0.06928030  1.345414e-01  0.0100175034  0.0166397745
 [20,] -0.06351469  1.329215e-01 -0.0736188358 -0.0344734444
 [21,] -0.06517277  1.193631e-01  0.0600481277 -0.0069852222
 [22,] -0.06329358  1.279082e-01 -0.0696249084  0.0222494332
 [23,] -0.05596085  1.406498e-01 -0.0830798653  0.0017258878
 [24,] -0.06295342  1.056799e-01 -0.0105187125  0.0784565109
 [25,] -0.06154560  1.017832e-01 -0.0304263956 -0.1601227105
 [26,] -0.05992289  1.046398e-01  0.0817625336  0.0177657222
 [27,] -0.06185719  1.130832e-01 -0.0273123325  0.0302188083
 [28,] -0.06293418  1.272214e-01  0.0149382892 -0.0068469837
 [29,] -0.06200349  1.281331e-01  0.0361582888  0.0354911952
 [30,] -0.05836687  1.059965e-01 -0.0007860890 -0.0669611777
 [31,] -0.05875351  1.045181e-01  0.0332336030 -0.0331081739
 [32,] -0.06445351  1.234731e-01  0.0324341677  0.1238084447
 [33,] -0.06513574  1.476264e-01 -0.0866079057 -0.1477304190
 [34,] -0.06752039  1.575598e-01 -0.0763976236 -0.0481030203
 [35,] -0.05900164  1.101081e-01  0.0494523876  0.0094187857
 [36,] -0.05857663  1.267564e-01  0.0495798107  0.0861257684
 [37,] -0.06421316  1.400014e-01  0.0618850969  0.0952278278
 [38,] -0.06027249  1.314248e-01 -0.0308738078 -0.0891264708
 [39,] -0.05362268  1.070098e-01 -0.0001642595 -0.0078414294
 [40,] -0.06175536  1.225431e-01  0.0199395042 -0.0070357644
 [41,] -0.06047448  1.300665e-01 -0.0261776218  0.0500141326
 [42,] -0.05180777  8.512648e-02  0.1354016274  0.1668950097
 [43,] -0.05441485  1.131665e-01 -0.0391851665 -0.0415056525
 [44,] -0.06260324  1.122916e-01 -0.0778558381  0.0931682290
 [45,] -0.06582810  1.150265e-01 -0.0959735460 -0.0966069476
 [46,] -0.05746319  1.074848e-01  0.0406466225  0.0746268384
 [47,] -0.06387433  1.308665e-01 -0.0598118558 -0.0998702779
 [48,] -0.05651492  1.123765e-01 -0.0118762355 -0.0329699353
 [49,] -0.06450909  1.349781e-01 -0.0095733792 -0.0234903145
 [50,] -0.06004194  1.218548e-01  0.0266502652  0.0182815222
 [51,] -0.09504224 -4.113264e-03  0.0937321578  0.0125204510
 [52,] -0.08945161 -7.668187e-03 -0.0054207074  0.0012979982
 [53,] -0.09510761 -1.870655e-02  0.0797977546  0.0012103018
 [54,] -0.07581925 -2.595322e-02  0.0791710094  0.0473477760
 [55,] -0.08918460 -2.237154e-02  0.0854207991  0.0601412693
 [56,] -0.08203819 -2.731153e-02  0.0020894889 -0.1303013338
 [57,] -0.09030916 -1.610480e-02 -0.0583760176 -0.0436763742
 [58,] -0.06725177  1.260061e-03  0.0311215251 -0.0127395163
 [59,] -0.09001346 -1.382327e-02  0.1114526362 -0.0194514823
 [60,] -0.07469578 -1.638481e-02 -0.0562055002 -0.0056465135
 [61,] -0.06751936 -1.743329e-02  0.1202534855  0.0205976875
 [62,] -0.08314196 -9.854827e-03 -0.0338173550  0.0263759619
 [63,] -0.07881188 -1.522669e-02  0.2177772338  0.0296120505
 [64,] -0.08680939 -2.774819e-02  0.021680371

In [46]:
sigma <- sing$d * diag(4)
v <- sing$v
sigma

[,1]     [,2]     [,3]     [,4]
[1,] 95.95991  0.00000 0.000000 0.000000
[2,]  0.00000 17.76103 0.000000 0.000000
[3,]  0.00000  0.00000 3.460931 0.000000
[4,]  0.00000  0.00000 0.000000 1.884826

And we can estimate our covariance matrix (to a scalar multiple) using the following approximation
    $$ covmat(x) \approx {\bf v\cdot\sum^{T}\cdot\sum v^{T}}$$

In [51]:
as.matrix(covmat)

Sepal.Length Sepal.Width Petal.Length Petal.Width
Sepal.Length    0.6856935  -0.0424340    1.2743154   0.5162707
Sepal.Width    -0.0424340   0.1899794   -0.3296564  -0.1216394
Petal.Length    1.2743154  -0.3296564    3.1162779   1.2956094
Petal.Width     0.5162707  -0.1216394    1.2956094   0.5810063

In [49]:
neweigs = eigen(v %*% t(sigma) %*% sigma * t(v))
neweigs

$values
[1] 5203.083501   94.992790   -8.623728    1.885648

$vectors
            [,1]        [,2]          [,3]          [,4]
[1,] -0.89066784 0.004274605 -0.0002406141  1.496831e-05
[2,]  0.17386643 0.566545202  0.0525600383 -5.540990e-03
[3,]  0.41112917 0.795952998 -0.9928141985  2.437743e-02
[4,]  0.08633694 0.213230125  0.1075051243  9.996875e-01

In [50]:
neweigs$values / sum(neweigs$values)

[1]  0.983320909  0.017952508 -0.001629782  0.000356365

Now although the matrix is different, and the factors are different, the approximations are about the same. Usually that is good enough to pick a certain number of components and start looking for them reducing computation time significantly. YOu can also just use these loadings as well and be happy with the results

## Last Ditch: NIPALS

Nipals, Non iterative partial least squares, the last method

In [71]:
install.packages('matrixcalc')
library(matrixcalc)

Installing package into ‘/home/bhuvan/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)


In [97]:
nipals1 <- function(X, tol=.01){
    X <- as.matrix(X)
    u <- rep(1/sqrt(dim(X)[2]), dim(X)[2])
    w <- rep(1, dim(X)[1])
    while(frobenius.norm(X-(w %o% u)) > tol){
        wint <- as.vector(X %*% u / (sum(u*u)))
        uint <- as.vector(t(X) %*% wint / (sum(wint*wint)))
        s <- sqrt(sum(uint*uint))
        u <- uint / s
        w <- wint * s
    }
    sum(u*w)
}


So here is how this algorithm works. U is a l2 normed vector and w is another vector. You update the vector by dotting X with the U vector and updating W with a dot from the other way. There is good statistical proofs into how this works (full proof in my mind and notebook, but google has its benefits). You use this to find an the highest value eigenvalue and then find the corresponding eigenvector.

## Conclusion

We have talked about principal components in excruciating detail an its optimizations -- the use of PCA will be used in later machine learning algorithms to increase generalizability. Other dimensionality reductions will be discussed next time 